web:
  restart: always
  build: ./app
  expose: 
    - "8000"
  volumes:
    - /usr/src/app/static
  env_file: 
    - .env_file
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

MongoDB:
  image: sameersbn/mongodb:latest
  ports:
    - "27017:27017"
  volumes:
    - /srv/docker/mongodb:/var/lib/mongodb
  restart: always
